title: "ML for Natural Sciences"
author: "Paolo Bonfini"
copyright: "2025"

html:
  extra_css:
    - _static/custom.css
  static_path:
    - chapters/chapter1/images

repository:
  url: https://github.com/gitpeblo/ML_book
  path_to_book: ML_book_site
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image