title: "ML Book"
author: "Paolo Bonfini"
copyright: "2025"

html:
  extra_css:
    - _static/custom.css

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "notebook"
  thebe: false

repository:
  url: https://github.com/<USER>/<REPO>  # Replace with your repo
  path_to_book: chapters                 # Path where notebooks are stored
  branch: main                           # Change if using a different branch
