title: "ML Book"
author: "Paolo Bonfini"
copyright: "2025"

html:
  extra_head: |
    <style>
      /* Force notebook cells to display in one column */
      div.cell {
        display: block !important;
        width: 100% !important;
        float: none !important;
        clear: both !important;
      }
      div.output {
        display: block !important;
        width: 100% !important;
        float: none !important;
        clear: both !important;
      }
      .jp-OutputArea-output {
        max-width: 100% !important;
      }
    </style>



