title: "ML Book"
author: "Paolo Bonfini"
copyright: "2025"

html:
  extra_head: |
    <style>
      /* Force notebook content into one column */
      .bd-article-container {
        display: block !important;
        max-width: 100% !important;
      }
      div.cell, div.output, div.jp-Cell {
        float: none !important;
        clear: both !important;
        display: block !important;
        width: 100% !important;
      }
      .margin, .margin-caption {
        float: none !important;
        display: block !important;
        width: 100% !important;
      }
    </style>



