title: "ML for Data Science"
author: "Paolo Bonfini"
copyright: "2025"

copy_files:
  - chapters/**/images/*

html:
  extra_css:
    - _static/custom.css
  use_titles_from_toc: true  # overrides titles inside notebook files

repository:
  url: https://github.com/gitpeblo/ML_book
  path_to_book: ML_book_site
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"