title: "ML Book"
author: "Paolo Bonfini"
copyright: "2025"

html:
  extra_css:
    - _static/custom.css

repository:
  url: https://github.com/gitpeblo/ML_book
  path_to_book: ML_book_site/chapters
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"

