name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache Mambaforge environment to speed up builds
      # Cache key changes only if environment.yml changes
      - name: Cache mambaforge environment
        uses: actions/cache@v3
        with:
          path: ~/mambaforge/envs
          key: ${{ runner.os }}-mambaforge-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-mambaforge-

      # Cache conda package tarballs to avoid redownloads
      - name: Cache mambaforge packages
        uses: actions/cache@v3
        with:
          path: ~/mambaforge/pkgs
          key: ${{ runner.os }}-mambaforge-pkgs-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-mambaforge-pkgs-

      # Install Mambaforge (fast conda-forge based solver)
      - name: Install Mambaforge
        run: |
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O mambaforge.sh
          bash mambaforge.sh -b -p ~/mambaforge
          echo "$HOME/mambaforge/bin" >> $GITHUB_PATH

      # Create environment with mamba (Python pinned to 3.12 for stability)
      - name: Create ML_book environment
        run: |
          mamba env create -n ML_book -f environment.yml --yes || mamba env update -n ML_book -f environment.yml --yes
          mamba install -n ML_book ipykernel --yes
          source ~/mambaforge/bin/activate ML_book
          python -m ipykernel install --name ML_book --display-name "Python (ML_book)" --user

      # Build the book
      - name: Build the book
        run: |
          source ~/mambaforge/bin/activate ML_book
          jupyter-book build ML_book_site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ML_book_site/_build/html
          force_orphan: true
