name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda (with mamba)
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          miniforge-variant: Miniconda3
          miniforge-version: latest
          activate-environment: ML_book
          use-mamba: true
          auto-update-conda: true

      - name: Cache conda environment
        uses: actions/cache@v4
        with:
          path: /usr/share/miniconda3/envs/ML_book
          key: linux-conda-${{ hashFiles('environment.yml') }}

      - name: Create ML_book environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mamba env update -n ML_book -f environment.yml
          mamba install -n ML_book ipykernel --yes
          conda activate ML_book
          python -m ipykernel install --name ML_book --display-name "Python (ML_book)" --user

      - name: Build the book
        run: |
          conda activate ML_book
          jupyter-book build ML_book_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ML_book_site/_build/html
          force_orphan: true
