name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Miniconda first so that pkgs directory exists
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ML_book
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true

      # Debug step to confirm exact Conda pkgs path for caching
      - name: Debug conda path
        shell: bash -l {0}
        run: |
          echo "Searching for Conda pkgs directory..."
          conda info
          find $CONDA_PREFIX/.. -type d -name pkgs

      # Cache conda packages to speed up environment creation
      # We will update path with correct pkgs directory from above debug
      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: $CONDA_PREFIX/../pkgs
          key: ${{ runner.os }}-conda-pkgs-v1
          restore-keys: |
            ${{ runner.os }}-conda-pkgs-

      - name: Add ML_book kernel
        shell: bash -l {0}
        run: |
          python -m ipykernel install --name ML_book --display-name "Python (ML_book)" --user

      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter-book build ML_book_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ML_book_site/_build/html
          force_orphan: true
