name: deploy-book

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyter-book

      - name: Build the book
        run: |
          jupyter-book build ML_book_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ML_book_site/_build/html
          force_orphan: true   # ensures full refresh every time

